from django.urls import include, path

from task_manager.views import (
    CreateProjectView,
    CreateTaskView,
    MessageCreateView,
    PersonalTaskListView,
    PositionCreateView,
    PositionDeleteView,
    PositionListView,
    PositionUpdateView,
    TaskDetailView,
    TaskTypeCreateView,
    TaskTypeDeleteView,
    TaskTypeListView,
    TaskTypeUpdateView,
    TeamProjectListView,
    TeamProjectTaskListView,
    InboxListView,
    MessageDetailView,
    UpdateProjectView,
    UpdateTaskView,
    DeleteProjectView,
    DeleteTaskView,
)


urlpatterns = [
    path("<str:team_name>/", PersonalTaskListView.as_view(), name="home_page"),
    path(
        "<str:team_name>/projects",
        TeamProjectListView.as_view(),
        name="team_projects_list",
    ),
    path(
        "<str:team_name>/projects/create",
        CreateProjectView.as_view(),
        name="team_projects_create",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>/update",
        UpdateProjectView.as_view(),
        name="team_project_update",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>/delete",
        DeleteProjectView.as_view(),
        name="team_project_delete",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>",
        TeamProjectTaskListView.as_view(),
        name="team_project_tasks_list",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>/create",
        CreateTaskView.as_view(),
        name="team_project_task_create",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>/<int:pk_task>/",
        TaskDetailView.as_view(),
        name="team_project_task_detail",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>/<int:pk_task>/update",
        UpdateTaskView.as_view(),
        name="team_project_task_update",
    ),
    path(
        "<str:team_name>/projects/<int:pk_project>/<int:pk_task>/delete",
        DeleteTaskView.as_view(),
        name="team_project_task_delete",
    ),
    path("<str:team_name>/messages/", InboxListView.as_view(), name="inbox"),
    path(
        "<str:team_name>/messages/create",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "<str:team_name>/messages/<int:pk_message>/detail",
        MessageDetailView.as_view(),
        name="message_detail",
    ),
    path(
        "<str:team_name>/positions/",
        PositionListView.as_view(),
        name="position_list",
    ),
    path(
        "<str:team_name>/positions/create",
        PositionCreateView.as_view(),
        name="position_create",
    ),
    path(
        "<str:team_name>/positions/<int:pk_position>/update",
        PositionUpdateView.as_view(),
        name="position_update",
    ),
    path(
        "<str:team_name>/positions/<int:pk_position>/delete",
        PositionDeleteView.as_view(),
        name="position_delete",
    ),
    path(
        "<str:team_name>/task-types/",
        TaskTypeListView.as_view(),
        name="task_type_list",
    ),
    path(
        "<str:team_name>/task-types/create",
        TaskTypeCreateView.as_view(),
        name="task_type_create",
    ),
    path(
        "<str:team_name>/task-types/<int:pk_task_type>/update",
        TaskTypeUpdateView.as_view(),
        name="task_type_update",
    ),
    path(
        "<str:team_name>/task-types/<int:pk_task_type>/delete",
        TaskTypeDeleteView.as_view(),
        name="task_type_delete",
    ),
    
]


app_name = "task_manager"
