# Generated by Django 5.1.6 on 2025-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_project_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
    ]
