# Generated by Django 5.1.6 on 2025-02-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_project_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="is_completed",
            new_name="is_complited",
        ),
    ]
