# Generated by Django 5.1.6 on 2025-02-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="task_manager.task",
            ),
        ),
    ]
