# Generated by Django 5.1.6 on 2025-02-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0009_alter_comment_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagenew",
            old_name="readed",
            new_name="is_read",
        ),
    ]
