# Generated by Django 5.1.6 on 2025-02-25 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0010_rename_readed_messagenew_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageArchieve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("send_datetime", models.DateTimeField()),
                ("archive_time", models.DateTimeField(auto_now_add=True)),
                (
                    "from_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_worker_archieve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_worker_archieve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
