# Generated by Django 5.1.6 on 2025-02-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0011_messagearchieve"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagenew",
            name="is_archieve",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="MessageArchieve",
        ),
    ]
